server:
  port: 8071

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/timesheets?createDatabaseIfNotExist=true
    username: root
    password: test
  jpa:
    hibernate.ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    format_sql: true

  application:
    name: TIMESHEET-SERVICE